'use strict';
(()=>{
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)], scenes=$$('.scene'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let current=0,userMotion=true,raf=0;
 const motion=()=>userMotion&&!reduced.matches&&!document.hidden;
 function syncMotion(){document.body.classList.toggle('motion-off',!motion());$('#motion').setAttribute('aria-pressed',String(motion()));$('#motion').setAttribute('aria-label',motion()?'Выключить движение':'Включить движение');$('#motion').disabled=reduced.matches;if(!motion())$('#oil-video').pause();}
 $('#motion').addEventListener('click',()=>{userMotion=!userMotion;syncMotion()});reduced.addEventListener('change',syncMotion);document.addEventListener('visibilitychange',()=>{syncMotion();if(document.hidden)pauseFilm()});syncMotion();
 function mark(i){current=Math.max(0,Math.min(13,i));$('#counter').innerHTML=String(current+1).padStart(2,'0')+' <i>—</i> 14';$('#prev').disabled=current===0;$('#next').disabled=current===13;scenes.forEach((s,j)=>s.classList.toggle('active',j===current));const hash='#'+scenes[current].id;if(location.hash!==hash)history.replaceState(null,'',hash);}
 function go(i){mark(i);scenes[current].scrollIntoView({behavior:motion()?'smooth':'instant',block:'start'});}
 $('#prev').addEventListener('click',()=>go(current-1));$('#next').addEventListener('click',()=>go(current+1));$('.brand').addEventListener('click',e=>{e.preventDefault();go(0)});
 function read(){raf=0;let i=0;scenes.forEach((s,j)=>{if(s.getBoundingClientRect().top<=innerHeight*.42)i=j});if(i!==current)mark(i)}
 addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(read)},{passive:true});addEventListener('resize',read);addEventListener('hashchange',()=>go(Math.max(0,scenes.findIndex(s=>'#'+s.id===location.hash))));
 const index=Math.max(0,scenes.findIndex(s=>'#'+s.id===location.hash));mark(index);addEventListener('load',()=>{scenes[index].scrollIntoView({behavior:'instant'});read()});
 const detail=$('#detail-dialog'),contents=$('#contents-dialog');
 function showDetail(title,html){$('#detail-title').textContent=title;$('#detail-body').innerHTML=html;detail.showModal();}
 $$('.note-link').forEach(b=>b.addEventListener('click',()=>showDetail(b.closest('.scene').querySelector('h1,h2').innerText.replaceAll('\n',' '),$('#'+b.dataset.note).innerHTML)));
 $$('.dialog-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
 $$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
 $('#contents-list').innerHTML=scenes.map((s,i)=>'<a href="#'+s.id+'" data-go="'+i+'"><span>'+String(i+1).padStart(2,'0')+'</span>'+s.querySelector('h1,h2').innerText.replaceAll('\n',' ')+'</a>').join('');
 $('#contents-open').addEventListener('click',()=>contents.showModal());$$('[data-go]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();contents.close();go(+a.dataset.go)}));$('#sources-open').addEventListener('click',()=>showDetail('Источники и материалы',$('#sources-template').innerHTML));
 document.addEventListener('keydown',e=>{if($('dialog[open]')||e.target.closest('input,button,a,summary'))return;if(e.key==='ArrowRight'){e.preventDefault();go(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(current-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(13)}});
 function selectButtons(selector,current){$$(selector).forEach(b=>b.setAttribute('aria-pressed',String(b===current)))}
 const causes=['Качество жиров и привычки','Наследственные особенности обмена','Заболевания и некоторые лекарства'];$$('[data-cause]').forEach(b=>b.addEventListener('click',()=>{selectButtons('[data-cause]',b);$('#cause-result').textContent=causes[+b.dataset.cause]}));
 let lipid='ldl';const lipids={ldl:{name:'Холестерин',carrier:'в составе ЛПНП',rgb:'134,107,69'},hdl:{name:'Холестерин',carrier:'в составе ЛПВП',rgb:'99,126,94'},tg:{name:'Триглицериды',carrier:'в составе липопротеинов',rgb:'159,110,87'}};
 $$('[data-lipid]').forEach(b=>b.addEventListener('click',()=>{lipid=b.dataset.lipid;selectButtons('[data-lipid]',b);const s=lipids[lipid];$('#orbital-name').textContent=s.name;$('#orbital-carrier').textContent=s.carrier;$('#lipid-result').textContent=s.name+' '+s.carrier;drawOrbit()}));
 const canvas=$('#orbit'),ctx=canvas.getContext('2d');let w=0,h=0,angle=0,orbitVisible=false,last=0;
 const particles=Array.from({length:260},(_,i)=>{const phi=Math.acos(1-2*(i+.5)/260),theta=Math.PI*(3-Math.sqrt(5))*i;return{x:Math.sin(phi)*Math.cos(theta),y:Math.cos(phi),z:Math.sin(phi)*Math.sin(theta),r:1+(i%5)*.24,i}});
 function resizeOrbit(){const rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx?.setTransform(dpr,0,0,dpr,0,0);drawOrbit()}
 function drawOrbit(){if(!ctx||!w||!h)return;const rgb=lipids[lipid].rgb,cx=w/2,cy=h*.48,r=Math.min(w*.3,h*.32);ctx.clearRect(0,0,w,h);const glow=ctx.createRadialGradient(cx,cy,r*.1,cx,cy,r*1.65);glow.addColorStop(0,'rgba('+rgb+',.08)');glow.addColorStop(1,'rgba('+rgb+',0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
 for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(cx,cy,r*(1.23+i*.13),r*(.4+i*.13),-.55+i*.69+angle*.12,0,Math.PI*2);ctx.strokeStyle='rgba('+rgb+',.22)';ctx.lineWidth=.8;ctx.stroke();}
 const points=particles.map(p=>{const x=p.x*Math.cos(angle)-p.z*Math.sin(angle),z=p.x*Math.sin(angle)+p.z*Math.cos(angle),pers=1.5/(1.5+z*.35);return{x:cx+x*r*pers,y:cy+p.y*r*pers,z,r:p.r*pers}}).sort((a,b)=>b.z-a.z);
 points.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='rgba('+rgb+','+(.24+(1-p.z)*.29)+')';ctx.fill()});ctx.beginPath();ctx.arc(cx,cy,r*.51,0,Math.PI*2);ctx.strokeStyle='rgba('+rgb+',.2)';ctx.stroke();}
 new ResizeObserver(resizeOrbit).observe(canvas);new IntersectionObserver(e=>{orbitVisible=e[0].isIntersecting;if(orbitVisible)resizeOrbit()},{threshold:.01}).observe(canvas);
 function tick(t){if(orbitVisible&&motion()){if(last)angle+=Math.min(t-last,80)*.00010;drawOrbit()}last=t;requestAnimationFrame(tick)}resizeOrbit();requestAnimationFrame(tick);
 const oil=$('#oil-video');$('#oil-play').addEventListener('click',()=>{if(reduced.matches){$('#oil-play').textContent='Движение выключено настройкой устройства';return}if(!oil.paused){oil.pause();return}const source=oil.querySelector('source');if(!source.src){source.src=source.dataset.src;oil.load()}if(oil.ended)oil.currentTime=0;oil.play().then(()=>{oil.classList.add('ready');$('#oil-play').textContent='Остановить наливание'}).catch(()=>{$('#oil-play').textContent='Видео недоступно · показано фото'})});oil.addEventListener('ended',()=>$('#oil-play').textContent='Повторить · 1,5 с ↗');oil.addEventListener('pause',()=>{if(!oil.ended)$('#oil-play').textContent='Продолжить наливание ↗'});new IntersectionObserver(e=>{if(!e[0].isIntersecting)oil.pause()}).observe(oil);
 function setSwap(n){$('.swap-hero').style.setProperty('--swap',n+'%');$('#swap-range').value=n;$$('[data-swap]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.swap===n)));$('#swap-label').textContent=n===0?'Сливочное масло':n===100?'Оливковое масло':'Одна замена в привычном блюде'}
 $$('[data-swap]').forEach(b=>b.addEventListener('click',()=>setSwap(+b.dataset.swap)));$('#swap-range').addEventListener('input',e=>setSwap(+e.target.value));
 const foods=['Овощи к привычному обеду','Нут в суп или основное блюдо','Цельнозерновой хлеб к завтраку'];$$('[data-food]').forEach(b=>b.addEventListener('click',()=>{selectButtons('[data-food]',b);$('#food-result').textContent=foods[+b.dataset.food];$$('[data-pin]').forEach(p=>p.classList.toggle('active',p.dataset.pin===b.dataset.food))}));
 const pack=$('#package');let turned=false;$('#package-turn').addEventListener('click',()=>{turned=!turned;pack.classList.toggle('turned',turned);$('#package-turn').setAttribute('aria-pressed',String(turned));$('#package-turn').textContent=turned?'Вернуть лицевую сторону ↗':'Повернуть упаковку ↗';$('.package .front').setAttribute('aria-hidden',String(turned));$('.package .back').setAttribute('aria-hidden',String(!turned));$('.package .front').inert=turned;$('.package .back').inert=!turned;$('#package-result').textContent=turned?'Выберите строку на этикетке':'Состав и порция важнее обещаний'});
 const fields=['Сравните содержание в одинаковом количестве','Соль сравнивайте с солью, натрий — с натрием','Проверьте состав на сахар и сиропы','Учтите и состав, и свою фактическую порцию'];$$('[data-field]').forEach(b=>b.addEventListener('click',()=>{selectButtons('[data-field]',b);$('#package-result').textContent=fields[+b.dataset.field]}));
 let revealed=false;const risk={smoking:['Не курит','Курит'],pressure:['АД не повышено','АД повышено'],family:['Нет известных ранних событий','Раннее событие у родственника']};
 function setRisk(key){$('#risk-a').textContent=risk[key][0];$('#risk-b').textContent=risk[key][1]}
 $('#risk-reveal').addEventListener('click',()=>{revealed=!revealed;$('#risk-reveal').setAttribute('aria-expanded',String(revealed));$('#risk-reveal').textContent=revealed?'Скрыть контекст ↗':'Раскрыть контекст ↗';$('#risk-choices').hidden=!revealed;if(revealed){const selected=$('[data-risk][aria-pressed=true]');setRisk(selected.dataset.risk)}else{$('#risk-a').textContent='ХС-ЛПНП';$('#risk-b').textContent='Одинаковый'}});$$('[data-risk]').forEach(b=>b.addEventListener('click',()=>{selectButtons('[data-risk]',b);setRisk(b.dataset.risk)}));
 const qs=['Каков мой общий сердечно-сосудистый риск?','Какая цель по ХС-ЛПНП подходит мне?','Что изменить и когда оценить результат?'];$$('[data-question]').forEach(b=>b.addEventListener('click',()=>showDetail(qs[+b.dataset.question],'<p>Обсудите этот вопрос с врачом с учётом имеющихся анализов, истории заболеваний и назначенного лечения. Дополнительные исследования и сроки повторной оценки определяются индивидуально.</p>')));
 $$('[data-habit]').forEach(b=>b.addEventListener('click',()=>{selectButtons('[data-habit]',b);$('#s13').classList.add('chosen');$('#habit-result').textContent=b.dataset.habit}));
 const film=$('#film-dialog'),base='../consolidated/assets/';let elapsed=0,playing=false,filmFrame=0,filmLast=0,shot=-1;
 const shots=[['food.webp','Сердце<br>на вашей тарелке.'],['hero-reference-pair.png','Готовить вместе.<br>Жить вкусно.'],['butter-spread-start.png','Маленькие решения.<br>Каждый день.'],['fats.webp','Менять привычки.<br>Сохранять любимое.'],['portraits.webp','Ваш контекст.<br>Ваш темп.'],['walk.webp','Забота о сердце<br>продолжается дома.']];
 function paintFilm(){const next=Math.min(5,Math.floor(elapsed/5));if(next!==shot){shot=next;$('#film-image').src=base+shots[shot][0];$('#film-copy').innerHTML=shots[shot][1]}$('#film-progress').value=elapsed;$('#film-time').textContent='0:'+String(Math.floor(elapsed)).padStart(2,'0')+' / 0:30';$('#film-pause').textContent=playing?'Пауза':elapsed>=30?'Повторить':'Продолжить'}
 function frameFilm(t){if(!playing)return;elapsed=Math.min(30,elapsed+(t-filmLast)/1000);filmLast=t;paintFilm();if(elapsed>=30){playing=false;paintFilm();return}filmFrame=requestAnimationFrame(frameFilm)}
 function playFilm(){if(elapsed>=30)elapsed=0;playing=true;filmLast=performance.now();cancelAnimationFrame(filmFrame);paintFilm();filmFrame=requestAnimationFrame(frameFilm)}
 function pauseFilm(){playing=false;cancelAnimationFrame(filmFrame);paintFilm()}
 $('#showreel').addEventListener('click',()=>{elapsed=0;shot=-1;film.showModal();if(reduced.matches){pauseFilm()}else playFilm();$('#film-close').focus()});$('#film-close').addEventListener('click',()=>film.close());film.addEventListener('close',()=>{pauseFilm();$('#showreel').focus()});$('#film-pause').addEventListener('click',()=>playing?pauseFilm():playFilm());$('#film-restart').addEventListener('click',()=>{elapsed=0;shot=-1;playFilm()});
})();
